version: "2"
run:
  build-tags:
    - preview.query
linters:
  enable:
    - dogsled
    - dupl
    - errcheck
    - gocognit
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    dupl:
      threshold: 200
  exclusions:
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
          - typecheck
        path: _test\.go
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - docs/assets/snippets/.*\.go$
formatters:
  enable:
    - gofmt
