repo_url: https://github.com/michaeldcanady/servicenow-sdk-go
site_name: Service-Now SDK for Go Docs
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight
  - admonition
  - toc:
      permalink: true

plugins:
  - placeholder:
      enabled: True
      js_output_dir: "assets/javascript/"
      placeholder_css: "assets/css/placeholder-plugin.css"
      placeholder_extra_js: ""
      placeholder_file: "placeholder-plugin.yaml"
  - include-markdown

nav:
  - Welcome: index.md
  - User Guide:
      - Getting Started: getting-started.md
      - Authentication: user-guide/authentication.md
      - Table Operations: user-guide/tables.md
      - Attachments: user-guide/attachments.md
      - Batch Operations: user-guide/batch.md
      - Preview Features: user-guide/preview-features.md
      - Query Builder (Preview): user-guide/query-builder.md
  - API Reference:
      - Overview: apis/index.md
      - Table API:
          - Overview: apis/tables/index.md
          - List Records: apis/tables/list.md
          - Create Record: apis/tables/create.md
          - Get Record: apis/tables/get.md
          - Update Record: apis/tables/update.md
          - Delete Record: apis/tables/delete.md
      - Attachment API:
          - Overview: apis/attachment/index.md
          - File:
              - Overview: apis/attachment/file/index.md
              - Get: apis/attachment/file/get.md
              - Create: apis/attachment/file/create.md
          - Upload:
              - Overview: apis/attachment/upload/index.md
              - Create: apis/attachment/upload/create.md
          - List: apis/attachment/list.md
          - Get: apis/attachment/get.md
          - Delete: apis/attachment/delete.md
      - Batch API:
          - Overview: apis/batch/index.md
          - Create: apis/batch/create.md
  - Contributor Guide:
      - Overview: contributing/index.md
      - Development Setup: contributing/setup.md
      - Architecture: contributing/architecture.md
      - Testing: contributing/testing.md
  - Releases ⧉: https://github.com/michaeldcanady/servicenow-sdk-go/releases
  - Roadmap ⧉: https://github.com/users/michaeldcanady/projects/7/views/9

theme:
  font:
    text: Work Sans
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: teal
      accent: indigo
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: indigo
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
