name: Go dependency checks
description: Verifies that the go.sum file is consistent with the go.mod file.

inputs:
  mod-root:
    description: "Root directory containing go.mod/go.sum. Defaults to repository root."
    required: false
    default: ""
  go-version:
    description: "The Go version to use for the checks. If not specified, the version from the go.mod file will be used."
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: resolve mod path
      id: resolve-mod-path
      shell: bash
      run: |
        ROOT_PATH="${INPUT_MOD_ROOT:-$(git rev-parse --show-toplevel)}"
        GO_MOD_PATH="$ROOT_PATH/go.mod"
        GO_SUM_PATH="$ROOT_PATH/go.sum"
        if [[ ! -f "$GO_MOD_PATH" ]]; then
          echo "go.mod not found in $ROOT_PATH"
          exit 1
        fi
        if [[ ! -f "$GO_SUM_PATH" ]]; then
          echo "go.sum not found in $ROOT_PATH"
          exit 1
        fi
        echo "MOD_PATH=$GO_MOD_PATH" >> $GITHUB_OUTPUT
        echo "SUM_PATH=$GO_SUM_PATH" >> $GITHUB_OUTPUT
      env:
        INPUT_MOD_ROOT: ${{ inputs.mod-root }}

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
      with:
        go-version-file: ${{ steps.resolve-mod-path.outputs.MOD_PATH }}
        go-version: ${{ inputs.go-version }}

    - name: Verify dependencies
      shell: bash
      run: |
        cd "$(dirname "$MOD_PATH")"
        go mod verify
      env:
        MOD_PATH: ${{ steps.resolve-mod-path.outputs.MOD_PATH }}

    - name: Tidy dependencies
      shell: bash
      run: |
        cd "$(dirname "$MOD_PATH")"
        go mod tidy
        git diff --exit-code -- $MOD_PATH $SUM_PATH
      env:
        MOD_PATH: ${{ steps.resolve-mod-path.outputs.MOD_PATH }}
        SUM_PATH: ${{ steps.resolve-mod-path.outputs.SUM_PATH }}