package cdmapplicationsapi

import (
	abstractions "github.com/microsoft/kiota-abstractions-go"
)

// SharedLibrariesComponentsApplicationsRequestBuilderGetRequestConfiguration represents the GET request configuration for the Shared Libraries Components Applications resource.
type SharedLibrariesComponentsApplicationsRequestBuilderGetRequestConfiguration = abstractions.RequestConfiguration[SharedLibrariesComponentsApplicationsRequestBuilderGetQueryParameters]
