package ast

type ReferenceOperator int64

const (
	ReferenceOperatorIs ReferenceOperator = iota
	ReferenceOperatorIsNot
	ReferenceOperatorIsEmpty
	ReferenceOperatorIsNotEmpty
	ReferenceOperatorStartsWith
	ReferenceOperatorEndsWith
	ReferenceOperatorContains
	ReferenceOperatorDosNotContain
	ReferenceOperatorIsAnything
	ReferenceOperatorIsSame
	ReferenceOperatorIsDifferent
	ReferenceOperatorIsEmptyString
	ReferenceOperatorIsDynamic
)
