package core

// RelationalOperator ...
type RelationalOperator string

const (
	// Null ...
	Null RelationalOperator = ""
	// Is ...
	Is RelationalOperator = "="
	// IsNot ...
	IsNot RelationalOperator = "!="
	// GreaterThan ...
	GreaterThan RelationalOperator = ">"
	// GreaterOrEqual ...
	GreaterOrEqual RelationalOperator = ">="
	// LessThan ...
	LessThan RelationalOperator = "<"
	// LessOrEqual ...
	LessOrEqual RelationalOperator = "<="
	// Contains ...
	Contains RelationalOperator = "CONTAINS"
	// NotContains ...
	NotContains RelationalOperator = "!CONTAINS"
	// StartsWith ...
	StartsWith RelationalOperator = "STARTSWITH"
	// EndsWith ...
	EndsWith RelationalOperator = "ENDSWITH"
	// Between ...
	Between RelationalOperator = "BETWEEN"
	// IsSame ...
	IsSame RelationalOperator = "SAMEAS"
	// IsDifferent ...
	IsDifferent RelationalOperator = "NSAMEAS"
	// IsEmpty ...
	IsEmpty RelationalOperator = "ISEMPTY"
)
