package appointmentbookingapi

import abstractions "github.com/microsoft/kiota-abstractions-go"

// ConfigurationRequestBuilderGetRequestConfiguration represents the configuration for GET /configuration.
type ConfigurationRequestBuilderGetRequestConfiguration = abstractions.RequestConfiguration[ConfigurationRequestBuilderGetQueryParameters]
