package appointmentbookingapi

import abstractions "github.com/microsoft/kiota-abstractions-go"

// ExecuteRuleConditionsRequestBuilderPostRequestConfiguration represents the configuration for POST /execute_rule_conditions.
type ExecuteRuleConditionsRequestBuilderPostRequestConfiguration = abstractions.RequestConfiguration[abstractions.DefaultQueryParameters]
