package policyapi

import abstractions "github.com/microsoft/kiota-abstractions-go"

type PoliciesMappingsRequestBuilderDeleteRequestConfiguration = abstractions.RequestConfiguration[PolicyMappingsRequestBuilderDeleteQueryParameters]
