package actsubapi

import (
	abstractions "github.com/microsoft/kiota-abstractions-go"
)

// ActivitiesRequestBuilderGetRequestConfiguration represents the configuration for a GET request.
type ActivitiesRequestBuilderGetRequestConfiguration = abstractions.RequestConfiguration[abstractions.DefaultQueryParameters]

// ContextsRequestBuilderGetRequestConfiguration represents the configuration for a GET request.
type ContextsRequestBuilderGetRequestConfiguration = abstractions.RequestConfiguration[abstractions.DefaultQueryParameters]

// FacetsRequestBuilderGetRequestConfiguration represents the configuration for a GET request.
type FacetsRequestBuilderGetRequestConfiguration = abstractions.RequestConfiguration[abstractions.DefaultQueryParameters]

// FollowingsRequestBuilderGetRequestConfiguration represents the configuration for a GET request.
type FollowingsRequestBuilderGetRequestConfiguration = abstractions.RequestConfiguration[abstractions.DefaultQueryParameters]

// PreferencesRequestBuilderPostRequestConfiguration represents the configuration for a POST request.
type PreferencesRequestBuilderPostRequestConfiguration = abstractions.RequestConfiguration[abstractions.DefaultQueryParameters]

// PreferencesRequestBuilderGetRequestConfiguration represents the configuration for a GET request.
type PreferencesRequestBuilderGetRequestConfiguration = abstractions.RequestConfiguration[abstractions.DefaultQueryParameters]

// SubObjectsRequestBuilderGetRequestConfiguration represents the configuration for a GET request.
type SubObjectsRequestBuilderGetRequestConfiguration = abstractions.RequestConfiguration[abstractions.DefaultQueryParameters]

// SubscribersRequestBuilderGetRequestConfiguration represents the configuration for a GET request.
type SubscribersRequestBuilderGetRequestConfiguration = abstractions.RequestConfiguration[abstractions.DefaultQueryParameters]

// SubscriptionsRequestBuilderGetRequestConfiguration represents the configuration for a GET request.
type SubscriptionsRequestBuilderGetRequestConfiguration = abstractions.RequestConfiguration[abstractions.DefaultQueryParameters]

// IsSubscribedRequestBuilderGetRequestConfiguration represents the configuration for a GET request.
type IsSubscribedRequestBuilderGetRequestConfiguration = abstractions.RequestConfiguration[abstractions.DefaultQueryParameters]

// SubscribeRequestBuilderPostRequestConfiguration represents the configuration for a POST request.
type SubscribeRequestBuilderPostRequestConfiguration = abstractions.RequestConfiguration[abstractions.DefaultQueryParameters]

// UnsubscribeRequestBuilderDeleteRequestConfiguration represents the configuration for a DELETE request.
type UnsubscribeRequestBuilderDeleteRequestConfiguration = abstractions.RequestConfiguration[abstractions.DefaultQueryParameters]

// UserStreamRequestBuilderGetRequestConfiguration represents the configuration for a GET request.
type UserStreamRequestBuilderGetRequestConfiguration = abstractions.RequestConfiguration[abstractions.DefaultQueryParameters]

// UserStreamRequestBuilderPutRequestConfiguration represents the configuration for a PUT request.
type UserStreamRequestBuilderPutRequestConfiguration = abstractions.RequestConfiguration[abstractions.DefaultQueryParameters]
