package attachmentapi

import abstractions "github.com/microsoft/kiota-abstractions-go"

type AttachmentFileRequestBuilderPostRequestConfiguration = abstractions.RequestConfiguration[AttachmentFileRequestBuilderPostQueryParameters]
