package attachmentapi

import abstractions "github.com/microsoft/kiota-abstractions-go"

type TableAttachmentFileRequestBuilderPostRequestConfiguration = abstractions.RequestConfiguration[AttachmentFileRequestBuilderPostQueryParameters]
