package policyapi

import abstractions "github.com/microsoft/kiota-abstractions-go"

type PoliciesMappingsRequestBuilderPostRequestConfiguration = abstractions.RequestConfiguration[PoliciesMappingsRequestBuilderPostQueryParameters]
