import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Mirrors the former mkdocs.yml nav, split into one sidebar per navbar tab.

const sidebars: SidebarsConfig = {
  // Ordered as a reading path: set up → understand → connect → do → cope → peek ahead.
  userGuide: [
    'index',
    'getting-started',
    'core-concepts',
    'user-guide/migrate-v1-to-v2',
    'user-guide/configuration',
    {
      type: 'category',
      label: 'Authentication',
      link: {type: 'doc', id: 'user-guide/authentication/index'},
      items: [
        'user-guide/authentication/ropc',
        'user-guide/authentication/auth-code-private',
        'user-guide/authentication/auth-code-public',
        'user-guide/authentication/basic',
        'user-guide/authentication/client-credentials',
        'user-guide/authentication/jwt-token',
      ],
    },
    {
      type: 'category',
      label: 'APIs',
      items: [
        {
          type: 'category',
          label: 'Tables',
          link: {type: 'doc', id: 'user-guide/tables/index'},
          items: [
            'user-guide/tables/create-a-record',
            'user-guide/tables/list-and-query-records',
            'user-guide/tables/update-a-record',
            'user-guide/tables/delete-a-record',
          ],
        },
        {
          type: 'category',
          label: 'Attachments',
          link: {type: 'doc', id: 'user-guide/attachments/index'},
          items: [
            'user-guide/attachments/upload-from-disk',
            'user-guide/attachments/download-record-attachments',
            'user-guide/attachments/most-recent-attachment',
            'user-guide/attachments/delete-aging-attachments',
          ],
        },
        {type: 'category', label: 'Batch', items: ['user-guide/batch']},
        {type: 'category', label: 'Aggregation', items: ['user-guide/apis/stats/aggregate-records']},
        {type: 'category', label: 'Documents', items: ['user-guide/apis/documents/explore-documents']},
        {
          type: 'category',
          label: 'Activity Subscriptions',
          items: ['user-guide/apis/activity-subscriptions/check-subscriptions'],
        },
        {
          type: 'category',
          label: 'CMDB Instance',
          items: ['user-guide/apis/cmdb-instance/query-configuration-items'],
        },
        {type: 'category', label: 'Application Service', items: ['user-guide/apis/app-service/find-a-service']},
        {type: 'category', label: 'Case', items: ['user-guide/apis/case/read-cases']},
        {type: 'category', label: 'Account', items: ['user-guide/apis/account/read-accounts']},
        {
          type: 'category',
          label: 'Appointment Booking',
          items: ['user-guide/apis/appointment-booking/read-booking-configuration'],
        },
        {
          type: 'category',
          label: 'CDM Applications',
          items: ['user-guide/apis/cdm-applications/track-uploads'],
        },
        {type: 'category', label: 'CDM Changesets', items: ['user-guide/apis/cdm-changesets/track-changesets']},
        {type: 'category', label: 'CDM Editor', items: ['user-guide/apis/cdm-editor/edit-and-validate']},
        {type: 'category', label: 'Policy', items: ['user-guide/apis/policy/manage-mappings']},
      ],
    },
    'user-guide/pagination',
    'user-guide/error-handling',
    {
      type: 'category',
      label: 'Preview features',
      link: {type: 'doc', id: 'user-guide/preview-features'},
      items: ['user-guide/query-builder'],
    },
  ],
  apiReference: [
    'apis/index',
    {
      type: 'category',
      label: 'Table API',
      link: {type: 'doc', id: 'apis/tables/index'},
      items: [
        'apis/tables/list',
        'apis/tables/create',
        'apis/tables/get',
        'apis/tables/update',
        'apis/tables/delete',
      ],
    },
    {
      type: 'category',
      label: 'Attachment API',
      link: {type: 'doc', id: 'apis/attachment/index'},
      items: [
        {
          type: 'category',
          label: 'File',
          link: {type: 'doc', id: 'apis/attachment/file/index'},
          items: ['apis/attachment/file/get', 'apis/attachment/file/create'],
        },
        {
          type: 'category',
          label: 'Upload',
          link: {type: 'doc', id: 'apis/attachment/upload/index'},
          items: ['apis/attachment/upload/create'],
        },
        'apis/attachment/list',
        'apis/attachment/get',
        'apis/attachment/delete',
      ],
    },
    {
      type: 'category',
      label: 'Batch API',
      link: {type: 'doc', id: 'apis/batch/index'},
      items: ['apis/batch/create'],
    },
    {
      type: 'category',
      label: 'Aggregation API',
      link: {type: 'doc', id: 'apis/stats/index'},
      items: ['apis/stats/get-aggregates'],
    },
    {
      type: 'category',
      label: 'Documents API',
      link: {type: 'doc', id: 'apis/documents/index'},
      items: [
        'apis/documents/explore-documents',
        'apis/documents/create-document',
        'apis/documents/create-or-link-document',
        'apis/documents/delete-document',
        'apis/documents/get-document-content',
        'apis/documents/list-document-versions',
        'apis/documents/get-version-state',
        'apis/documents/sync-down-document',
        'apis/documents/attach-document',
        'apis/documents/execute-version-action',
      ],
    },
    {
      type: 'category',
      label: 'Activity Subscriptions API',
      link: {type: 'doc', id: 'apis/activity-subscriptions/index'},
      items: [
        'apis/activity-subscriptions/list-activities',
        'apis/activity-subscriptions/list-contexts',
        'apis/activity-subscriptions/list-subscription-objects',
        'apis/activity-subscriptions/get-facet-instances',
        'apis/activity-subscriptions/get-followings',
        'apis/activity-subscriptions/get-preference',
        'apis/activity-subscriptions/create-preference',
        'apis/activity-subscriptions/get-subscription',
        'apis/activity-subscriptions/check-subscription',
        'apis/activity-subscriptions/subscribe',
        'apis/activity-subscriptions/unsubscribe',
        'apis/activity-subscriptions/get-subscribers',
        'apis/activity-subscriptions/get-user-stream',
        'apis/activity-subscriptions/update-user-stream',
      ],
    },
    {
      type: 'category',
      label: 'CMDB & CSDM',
      items: [
        {
          type: 'category',
          label: 'CMDB Instance API',
          link: {type: 'doc', id: 'apis/cmdb-instance/index'},
          items: [
            'apis/cmdb-instance/list-configuration-items',
            'apis/cmdb-instance/create-configuration-item',
            'apis/cmdb-instance/get-configuration-item',
            'apis/cmdb-instance/update-configuration-item',
            'apis/cmdb-instance/patch-configuration-item',
            'apis/cmdb-instance/create-relation',
            'apis/cmdb-instance/delete-relation',
          ],
        },
        {
          type: 'category',
          label: 'Application Service API',
          link: {type: 'doc', id: 'apis/app-service/index'},
          items: [
            'apis/app-service/create-application-service',
            'apis/app-service/find-service',
            'apis/app-service/register-service',
            'apis/app-service/populate-service',
            'apis/app-service/update-service-details',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Customer Service',
      items: [
        {
          type: 'category',
          label: 'Case API',
          link: {type: 'doc', id: 'apis/case/index'},
          items: [
            'apis/case/list-cases',
            'apis/case/create-case',
            'apis/case/get-case',
            'apis/case/update-case',
            'apis/case/list-case-activities',
            'apis/case/get-case-field-values',
          ],
        },
        {
          type: 'category',
          label: 'Account API',
          link: {type: 'doc', id: 'apis/account/index'},
          items: ['apis/account/list-accounts', 'apis/account/get-account'],
        },
        {
          type: 'category',
          label: 'Appointment Booking API',
          link: {type: 'doc', id: 'apis/appointment-booking/index'},
          items: [
            'apis/appointment-booking/check-availability',
            'apis/appointment-booking/book-appointment',
            'apis/appointment-booking/get-calendar',
            'apis/appointment-booking/get-configuration',
            'apis/appointment-booking/execute-rule-conditions',
            'apis/appointment-booking/request-user-window',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Configuration Data Management',
      items: [
        {
          type: 'category',
          label: 'CDM Applications API',
          link: {type: 'doc', id: 'apis/cdm-applications/index'},
          items: [
            'apis/cdm-applications/update-deployables',
            'apis/cdm-applications/delete-deployables',
            'apis/cdm-applications/list-exports',
            'apis/cdm-applications/get-export-status',
            'apis/cdm-applications/get-export-content',
            'apis/cdm-applications/update-shared-components',
            'apis/cdm-applications/delete-shared-components',
            'apis/cdm-applications/list-shared-library-applications',
            'apis/cdm-applications/upload-components',
            'apis/cdm-applications/upload-component-vars',
            'apis/cdm-applications/upload-collections',
            'apis/cdm-applications/upload-collection-file',
            'apis/cdm-applications/upload-deployable-file',
            'apis/cdm-applications/get-upload-status',
          ],
        },
        {
          type: 'category',
          label: 'CDM Changesets API',
          link: {type: 'doc', id: 'apis/cdm-changesets/index'},
          items: [
            'apis/cdm-changesets/list-changesets',
            'apis/cdm-changesets/delete-changesets',
            'apis/cdm-changesets/get-changeset-activity',
            'apis/cdm-changesets/get-commit-status',
            'apis/cdm-changesets/list-impacted-deployables',
            'apis/cdm-changesets/list-impacted-shared-components',
            'apis/cdm-changesets/get-changeset-impacted-deployables',
          ],
        },
        {
          type: 'category',
          label: 'CDM Editor API',
          link: {type: 'doc', id: 'apis/cdm-editor/index'},
          items: [
            'apis/cdm-editor/list-nodes',
            'apis/cdm-editor/create-node',
            'apis/cdm-editor/update-node',
            'apis/cdm-editor/delete-node',
            'apis/cdm-editor/validate-configuration',
          ],
        },
        {
          type: 'category',
          label: 'Policy API',
          link: {type: 'doc', id: 'apis/policy/index'},
          items: ['apis/policy/create-policy-mapping', 'apis/policy/delete-policy-mapping'],
        },
      ],
    },
  ],
  // Tiered by contributor experience: land → first PR → understand → master → why.
  contributing: [
    'contributing/index',
    {
      type: 'category',
      label: 'Your first contribution',
      collapsed: false,
      items: ['contributing/setup', 'contributing/first-pr'],
    },
    {
      type: 'category',
      label: 'Understand the codebase',
      collapsed: false,
      items: ['contributing/architecture', 'contributing/testing'],
    },
    {
      type: 'category',
      label: 'Conventions & playbooks',
      collapsed: false,
      items: ['contributing/conventions', 'contributing/add-api-module'],
    },
    {
      type: 'category',
      label: "Why it's built this way",
      link: {type: 'doc', id: 'contributing/design-decisions'},
      items: [
        'contributing/design-hand-written-kiota',
        'contributing/design-backed-models',
        'contributing/design-error-handling',
      ],
    },
  ],
};

export default sidebars;
