name: Go CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "!docs/snippets/**"
      - ".github/workflows/go.yml"
  pull_request:
    paths:
      - "**.go"
      - "!docs/snippets/**"
      - ".github/workflows/go.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  COVERAGE_FILE: coverage.out

permissions: {}

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'release-please--'))
    outputs:
      code: ${{ steps.filter.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Changed Files
        uses: tj-actions/changed-files@v47.0.5
        id: filter
        with:
          files: |
            **.go
            !docs/snippets/**
            .github/workflows/go.yml

  check-go:
    name: Check Go Modules
    needs:
      - changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        go-versions: &go-versions ["stable", "oldstable"]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - run: go mod download
      - run: go mod verify
      - run: |
          go mod tidy
          git diff --exit-code -- .

  build-go:
    name: Build Go Code
    needs:
      - changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        os: &os-platforms [ubuntu-latest, macos-latest, windows-latest]
        go-version: *go-versions
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - run: go mod download
      - name: Build Go Code
        run: |
          PACKAGES=$(go list ./... | grep -v "/docs")
          go build $PACKAGES

  lint-go:
    name: Lint Go Code
    needs:
      - changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        go-version: *go-versions
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          skip-cache: false
          args: --timeout=5m

  test-go:
    name: Test Go Code
    needs:
      - changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        os: *os-platforms
        go-version: *go-versions
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: Run tests
        run: |
          PACKAGES=$(go list ./... | grep -v "/docs")
          COVERPKG=$(echo "$PACKAGES" | paste -sd "," -)
          go test -count=1 -tags=preview.query -coverpkg="$COVERPKG" -covermode=atomic -coverprofile=$COVERAGE_FILE $PACKAGES
          grep -v -E -f .covignore $COVERAGE_FILE > coverage.filtered.out && mv coverage.filtered.out $COVERAGE_FILE
          go tool cover -func=$COVERAGE_FILE
          go tool cover -html=$COVERAGE_FILE -o cover.html
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.os }}-coverage-report-${{ matrix.go-version }}-${{ hashFiles('go.sum') }}) }}
          path: cover.html
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
