name: PR Checks
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - main
      - "release/**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write # post/remove sticky comment for title lint
      contents: read # read PR metadata
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6
        id: lint_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            chore
            docs
            style
            refactor
            perf
            test
          requireScope: false
          postErrorComment: false

      - uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v2
        if: always() && steps.lint_title.outputs.error_message != ''
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request!

            We require that pull request titles follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.

            It looks like your proposed title needs to be adjusted.

            Details:
            ```
            ${{ steps.lint_title.outputs.error_message }}
            ```

      - uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v2
        if: ${{ !cancelled() && steps.lint_title.outputs.error_message == '' }}
        with:
          header: pr-title-lint-error
          delete: true

  dependabot-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    permissions:
      contents: write # gh pr merge --auto needs write to enable auto-merge
      pull-requests: write # enable auto-merge
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        if: ${{steps.metadata.outputs.update-type != 'version-update:semver-major'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
