name: Check License Headers

on:
  workflow_call:
    inputs:
      go-version:
        description: "Go version to use (e.g. stable, oldstable, 1.20)"
        required: false
        default: "stable"
        type: string
      config-path:
        description: "Path to license check config file"
        required: false
        default: ".github/license-check/license-config.json"
        type: string

permissions: {}

jobs:
  check-license:
    name: Check License Headers
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read # checkout and verify license headers
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-go-env
        with:
          go-version: ${{ inputs.go-version }}
          cache: "false"
          checkout: "false"
      - name: Verify license headers
        uses: viperproject/check-license-header@e06c65614fa9f32e099838df4dd25440c5344b32 # v2.0.3
        with:
          path: "."
          config: ${{ inputs.config-path }}
          strict: true