name: Check Snippets

on:
  workflow_call:

permissions: {}

jobs:
  snippets:
    name: Check Doc Snippets
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Vet Go snippets
        uses: ./.github/actions/vet-go-snippets

      - name: Check snippet regions
        uses: ./.github/actions/check-snippet-regions
