name: OpenSSF Scorecard

on:
  workflow_dispatch:
  branch_protection_rule:
  schedule:
    - cron: "30 1 * * 1"
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false # needs to complete each time

jobs:
  analysis:
    permissions:
      contents: read # Scorecard branch-protection check via GraphQL
      security-events: write # SARIF upload to code scanning
      id-token: write # OIDC token for publish_results
    uses: ./.github/workflows/reusable-scorecard.yaml
