name: Stable Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Create release
        uses: googleapis/release-please-action@v5
        id: release
        with:
          config-file: release-please-config.json
