name: Go Test

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "**.go"
      - ".github/workflows/lint.yml"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "**.go"
      - ".github/workflows/lint.yml"
      - ".github/workflows/test.yml"

env:
  COVERAGE_FILE: coverage.out

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.filter.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Changed Files
        uses: tj-actions/changed-files@v47.0.0
        id: filter
        with:
          files: "**.go"
  
  check-go:
    name: Check go
    if: ${{ needs.changes.outputs.all_changed_files == 'true' }}
    permissions:
      contents: read
    needs:
      - changes
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: ["1.23", "1.24"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
      
      - name: Download all Go modules
        run: |
          go mod download

      - name: Check for tidiness of go.mod and go.sum
        run: |
          go mod tidy
          git diff --exit-code -- .

  build-go:
    name: Build & cache Go code
    #if: ${{ needs.changes.outputs.backend == 'true' }}
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ["1.23", "1.24"]
    #needs:
    #  - changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
            go-version: ${{ matrix.go-version }}

      - name: Restore go build cache
        uses: actions/cache@v4.3.0
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-build-go-${{ github.run_id }}

      - name: Download all Go modules
        run: |
          go mod download
      
      - name: Build SDK project
        run: go build ./...

  lint-go:
    name: lint
    #if: ${{ needs.changes.outputs.all_changed_files == 'true' }}
    permissions:
      contents: read
    #needs:
    #  - changes
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: ["1.23", "1.24"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  test-go:
    name: Test
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ["1.23", "1.24"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go install ./...
        working-directory: ${{ github.workspace }}

      - name: Restore go build cache
        uses: actions/cache@v4.3.0
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-build-go-${{ github.run_id }}

      - name: Run unit tests on Unix systems
        if: runner.os != 'Windows'
        run: |
          go test -count=1 -tags=preview.query -coverpkg=./... -covermode=atomic -coverprofile $COVERAGE_FILE  ./...
          grep -v -E -f .covignore $COVERAGE_FILE > coverage.filtered.out && mv coverage.filtered.out $COVERAGE_FILE
        working-directory: ${{ github.workspace }}

      - name: Run unit tests on Windows systems
        if: runner.os == 'Windows'
        run: |
          go test -count=1 -tags="preview.query" -coverpkg=./... -covermode=atomic -coverprofile $env:COVERAGE_FILE  ./...
          findstr /V /G:.covignore $env:COVERAGE_FILE > coverage.filtered.out
          Move-Item -Path coverage.filtered.out -Destination $env:COVERAGE_FILE -Force
        working-directory: ${{ github.workspace }}

      - name: Generate Coverage File
        if: runner.os != 'Windows'
        run: go tool cover -html="${COVERAGE_FILE}" -o "cover.html"
        working-directory: ${{ github.workspace }}

      - name: Generate Coverage File
        if: runner.os == 'Windows'
        run: go tool cover -html="$($env:COVERAGE_FILE)" -o "cover.html"
        working-directory: ${{ github.workspace }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
