name: Create Weekly Preview Release

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday at midnight (UTC)
  workflow_dispatch: # Manual trigger

env:
  PREVIEW_VERSION:

jobs:
  create_preview_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Version
        id: read_version
        run: |
          unreleased_version=$(cat VERSION)
          echo "PREVIEW_VERSION=$unreleased_version-preview$(date +'%Y%m%d')" >> $GITHUB_ENV
        shell: bash

      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{env.PREVIEW_VERSION}}"
          message: "Preview Release $PREVIEW_VERSION"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "v${{env.PREVIEW_VERSION}}"
          prerelease: true
          title: Preview Release v${{env.PREVIEW_VERSION}}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            changelog.md
